# Node.js
# Build a general Node.js project with npm. test Auto trigger CI checking again again again
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# Testing

trigger:
- main

# no PR triggers
pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - task: Npm@1
    inputs:
      command: "install"

  - script: npm run build
    env:
      COSMOS_DB_KEY: ${COSMOS_DB_KEY}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
      STAFF_VIEW_ALLOWED_IPS: ${STAFF_VIEW_ALLOWED_IPS}
    displayName: "npm build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(build.sourcesDirectory)"
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts: drop"

  - task: Veracode@3
    inputs:
      ConnectionDetailsSelection: "Endpoint"
      AnalysisService: "Veracode  Scan"
      veracodeAppProfile: "$(system.teamProject)"
      version: "$(build.buildNumber)"
      filepath: "$(build.artifactstagingdirectory)"
      createSandBox: false
      createProfile: true
      failTheBuildIfVeracodeScanDidNotInitiate: false
      scanStatusCheckInterval: "60"
      importResults: false
      failBuildOnPolicyFail: false
